name: test
channels:
  - default
dependencies:
    # Base depends
  - cmake
  - numpy
  - python

    # Testing
  - pytest
  - pytest-cov

    # Pip depends
  - pip:
      # Base depends
    - pint

      # Testing
    - codecov
    - deepdiff
