name: test
channels:
  - defaults
  - psi4
  - conda-forge
dependencies:
    # Base depends
  - cmake
  - libefp
  - nomkl
  - numpy
  - pybind11
  - python
  - qcelemental >=0.4.0

    # Testing
  - pytest
  - pytest-cov
  - codecov

