name: test
channels:
  - defaults
  - conda-forge
  #- psi4
dependencies:
    # Base depends
  - cmake
  #- libefp
  - numpy
  - pybind11
  - python
  - qcelemental >=0.4.0

    # Testing
  - pytest
  - pytest-cov
  - codecov

