# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: cpp

# Run jobs on container-based infrastructure, can be overridden per job
sudo: false

# We do not work on the "trusty" container yet
dist: precise

matrix:
  include:

  - os: linux
    compiler: clang
    addons: &1
      apt:
        sources:
        - llvm-toolchain-precise-3.6
        - ubuntu-toolchain-r-test
        - george-edison55-precise-backports
        packages:
        - liblapack-dev
        - clang-3.6
    env:
      - CXX_COMPILER='clang++-3.6'
      - PYTHON_VER='3.6'
      - C_COMPILER='clang-3.6'

  - os: linux
    compiler: gcc
    addons: &3
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - george-edison55-precise-backports
        packages:
        - liblapack-dev
        - g++-4.9
        - gcc-4.9
    env:
      - CXX_COMPILER='g++-4.9'
      - PYTHON_VER='3.7'
      - C_COMPILER='gcc-4.9'

  - os: linux
    compiler: gcc
    addons: &4
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - george-edison55-precise-backports
        packages:
        - liblapack-dev
        - g++-6
        - gcc-6
    env:
      - CXX_COMPILER='g++-6'
      - PYTHON_VER='3.5'
      - C_COMPILER='gcc-6'

  - os: linux
    compiler: gcc
    addons: &5
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - george-edison55-precise-backports
        packages:
        - liblapack-dev
        - g++-6
        - gcc-6
    env:
      - CXX_COMPILER='g++-6'
      - PYTHON_VER='3.7'
      - C_COMPILER='gcc-6'

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a

  - source devtools/travis-ci/before_install.sh
  - conda info -a

install:
  # Build out environment
  #- conda create -n tenv python=$PYTHON_VER cmake numpy ci-psi4 psi4 -c psi4/label/dev
  - conda create -n tenv python=$PYTHON_VER cmake numpy deepdiff -c psi4
  - source activate tenv
  - conda install pytest pytest-cov codecov -c defaults -c conda-forge
  - conda list

before_script:
  - python -V
  - cd ${TRAVIS_BUILD_DIR}
  - ${C_COMPILER} --version
  - ${CXX_COMPILER} --version
  - >
      cmake -Bbuild -H.
      -DCMAKE_CXX_COMPILER=${CXX_COMPILER}
      -DCMAKE_C_COMPILER=${C_COMPILER}
      -DCMAKE_BUILD_TYPE=Release
      -DPYTHON_EXECUTABLE="${CONDA_PREFIX}/bin/python"
      -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/Install
      -DCMAKE_DISABLE_FIND_PACKAGE_libefp=ON
  - cd build
  - make -j2
      #-DLAPACK_LIBRARIES="${CONDA_PREFIX}/lib/libmkl_rt.so"
      #-DDISABLE_FIND_PACKAGE_TargetLAPACK=ON

script:
  - make install && cd .. && rm -rf pylibefp
  - export PYTHONPATH=${TRAVIS_BUILD_DIR}/Install/lib/:$PYTHONPATH
  - python -c "import pylibefp; print(pylibefp.__version__)"
  - conda install ci-psi4 psi4 -c psi4/label/dev
  - python -c "import sys, pylibefp; sys.exit(pylibefp.test())"
  #- python -c "import sys, pylibefp; sys.exit(pylibefp.test(extras=['--cov']))"
  #- python -c "import sys, pylibefp; sys.exit(pylibefp.test(extras=['-k', 'not qmefp', '--cov']))"

  # works but overcomplicated
  #- make pytest VERBOSE=1
  ##- PYTHONPATH=stage/usr/local/pylibefp/lib/ pytest -v --cov --ignore=external ../tests/
  ##- cd ../tests && PYTHONPATH=../build/stage/usr/local/pylibefp/lib/ python -m pytest -v --ignore=../build/external --cov
  #- cd ${TRAVIS_BUILD_DIR}/build/tests && PYTHONPATH=${TRAVIS_BUILD_DIR}/build/stage/${TRAVIS_BUILD_DIR}/Install/lib/ /home/travis/miniconda/envs/tenv/bin/python -m pytest -rws -v --capture=sys ${TRAVIS_BUILD_DIR}/tests --ignore=${TRAVIS_BUILD_DIR}/build/external --cov

notifications:
    email: false

after_success:
  - codecov
