clone_depth: 1
platform: x64

image:
  - Visual Studio 2017

configuration:
  - Debug

install:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - C:\Miniconda36-x64\Scripts\activate base
  - conda install --yes cmake python=3.6 numpy deepdiff pytest pytest-cov codecov -c defaults -c conda-forge
  - conda list

before_build:
  - mkdir build && cd build
  - cmake -A %PLATFORM%
          -DCMAKE_BUILD_TYPE=%CONFIGURATION%
          -DENABLE_XHOST=OFF
          -DCMAKE_C_FLAGS="/wd4101 /wd4996"
          -DCMAKE_CXX_FLAGS="/wd4101 /wd4996"
          ..

build_script:
  - cmake --build .
          --config %CONFIGURATION%

after_build:
  - cmake --build .
          --config %CONFIGURATION%
          --target install

#########

#before_build:
#          -DCMAKE_C_FLAGS="/wd4018 /wd4101 /wd4996"
#          -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=true
#          -DINSTALL_PYMOD=ON
#          ..


before_test:
  - cd ..
  # Copy the library manualy as the installation is broken
  - copy build\Debug\gg.dll gau2grid\libgg.dll

test_script:
  - pytest


